name: AWS ECR Publish
author: Taylor Smith <taylor.smithgg@gmail.com>
branding:
  icon: upload-cloud
  color: orange
description: Create Docker images and push into a ECR repository.
inputs:
  account_id:
    description: AWS Account ID
    required: true
  assume_role:
    description: A role to assume under the account_id account.
    required: false
    default: ''
  repo:
    description: Name of your ECR repository
    required: true
  region:
    description: The AWS region
    required: true
  create_repo:
    description: Set this to true to create the repository if it does not already exist
    default: false
  set_repo_policy:
    description: Set this to true to set a policy on the repository
    default: false
  repo_policy_file:
    description: Set this to repository policy statement json file. only used if the set_repo_policy is set to true
    default: repo-policy.json
  tags:
    description: Comma-separated string of ECR image tags
    default: latest
  image_scanning_configuration:
    description: Set this to True if you want AWS to scan your images for vulnerabilities
    default: false
  dockerfile:
    description: Name of Dockerfile to use
    default: Dockerfile
  extra_build_args:
    description: Extra flags to pass to docker build (see docs.docker.com/engine/reference/commandline/build)
    default: ''
  cache_from:
    description: Images to use as cache for the docker build (see `--cache-from` argument docs.docker.com/engine/reference/commandline/build)
    default: ''
  path:
    description: Path to Dockerfile, defaults to the working directory
    default: .
  prebuild_script:
    description: Relative path from top-level to script to run before Docker build
    required: false
  postbuild_script:
    description: Relative path from top-level to script to run after Docker build
    required: false
  sub_modules:
    description: build sub modules that contain a dockerfile
    default: false
outputs:
  image:
    description: 'The created image name'
runs:
  using: docker
  image: Dockerfile
